export default [
  {
    id: "1",
    title: "katun jepang dino",
    price: 160000,
    offerPrice: null,
    stock: 12,
    img: "katun jepang dino.jpg",
    category: "katun jepang",
  },
  {
    id: "1",
    title: "katun jepang poppy",
    price: 160000,
    offerPrice: null,
    stock: 12,
    img: "katun jepang poppy.jpg",
    category: "katun jepang",
  },
  {
    id: "1",
    title: "katun lokal anak beruang",
    price: 160000,
    offerPrice: null,
    stock: 12,
    img: "katun lokal anak beruang.jpg",
    category: "katun lokal",
  },
  {
    id: "1",
    title: "katun lokal anak kelinci",
    price: 160000,
    offerPrice: null,
    stock: 12,
    img: "katun lokal anak kelinci.jpg",
    category: "katun lokal",
  },
  {
    id: "1",
    title: "katun lokal anak merah",
    price: 160000,
    offerPrice: null,
    stock: 12,
    img: "katun lokal anak merah.jpg",
    category: "katun lokal",
  },
  {
    id: "1",
    title: "tencel organik 60 polos",
    price: 160000,
    offerPrice: null,
    stock: 12,
    img: "tencel organik 60 polos.jpg",
    category: "tencel",
  },
];
